### ISSUE TITLE
[FEATURE REQ] BTC/USD Current Price Stamp Per Trade

### ISSUE THREAD

**Issue by Spitwod** [bTayFla/PtTracker#1]
Does the tool lock in the USD converted rate for each trade at the time of the trade? If you are in the US like me that's going to be needed come tax time. 
When expanding to show the daily trade history I see it stores everything but what the BTC/USD was at the exact time of the trade. This would be a great feature to add to this nice tool.

**Comment by woodyalien** [comment]
well, best would be to have it "selectable" as a switch for current price X price at the trade time... but I guess that would be hard to develop when still to guarantee consistency. Requires DB probably. I would like to hear about it from devs too.

For the specific purpose of tax reporting, I would suggest you getting cointracking, which has that as one of their goals.

**Comment by Spitwod** [comment]
After reading all the notes I see that it is very passive. So to implement,
it would probably need to reach out externally and possibly necessitate the
need for an API. Thanks for the reply.
