### ISSUE TITLE
[Issue] Blank screen from remote browser

### ISSUE THREAD

**Issue by tooraj-enayati** [bTayFla/PtTracker#10]
PT-Tracker works on my VPS accessing both via localhost and its public IP address. Occasionally when I try to connect to it remotely over the internet I get a blank page (no data/number). See the attached.

The strange thing is that PT-Tracker is running just fine on my VPS, but not over the internet.

I have to go to Task Manager and kill mongoose and restart PT-Tracker to recover from this. Maybe there should be a logfile for PT-Tracker.

![capture1](https://user-images.githubusercontent.com/24386973/36292418-d73a91b2-1325-11e8-9ca6-80b0dc95c9b1.JPG)

**Comment by clownfish44** [comment]
Your pttracker.json is messed up please make sure the format is correct.

**Comment by tooraj-enayati** [comment]
That doesn't make sense.

I only get this issue when I try to access it over the internet.

Plus if I restart PT-Tracker, without touching pttracker.json the issue is resolved!

**Comment by woodyalien** [comment]
@tooraj-enayati This also happened to me multiple times, but get resolved with a simple page reload (no need to restart PTT). Unsure your situation is that simple though.

**Comment by tooraj-enayati** [comment]
@clownfish44 I have worked it.  Your pttracker.net domain has stopped resolving for my home PC! I have just added it into the host file and all is good! 👍
