### ISSUE TITLE
No new day entry on Daily Profit Log

### ISSUE THREAD

**Issue by CryptoLaz** [bTayFla/PtTracker#103]
**Question i raised in Discord Channel and didn't get a response**

"Anyone....  could you please advise  which time period does PtT follows (when does it start and end the day). It is already 9.31AM here in Sydney 3 of April  but PTF has not started recording sales made today and I have made 16 closed trades already.  Is there are setting somewhere that i should configure?  My PT server.timeZoneOffset = +10:00 is correct. Thank you."

Thanks
LaZzA

**Comment by smoochy** [comment]
Probably related to https://github.com/bTayFla/PtTracker/issues/96

**Comment by CryptoLaz** [comment]
I been watching my PtT and it flicks the switch precisely at 00:00 UTC and ignores the server offs setting in my PT configurations file.

**Comment by CryptoLaz** [comment]
Similar with #96 but not exactly the same. Has there been attempt to review and address my issue (#103)? Thanks.

**Comment by LiamAird** [comment]
Please join the discord for help with these issues.

**Comment by LiamAird** [comment]
Timezone offset should be fixed in the next release. 
Next updat is scheduled around the same time as PT2.0

**Comment by CryptoLaz** [comment]
Thank you
