### ISSUE TITLE
Mismatch in Total Daily Sells in PT & PtT

### ISSUE THREAD

**Issue by samirsayz** [bTayFla/PtTracker#105]
The point of Tracker is that it should be tracking profits correctly. This is not happening because of the following issues:

1. Day does not restart at 12:00 AM on PtT
2. Therefore mismatch remains between PT & PtT

I believe issue #96 is discussing the same point!

You will see in the images below, that Profit Trailer is reflecting 20 sells for the day and PT Tracker is reflecting only 17 sells for the day. I purchased this software so I can have correct information captured automatically. My Excel sheet was more accurate than this. 

![pt](https://user-images.githubusercontent.com/34843697/38292304-e1c38210-3800-11e8-90a7-92705d0c3488.png)

![ptt](https://user-images.githubusercontent.com/34843697/38292313-e60cfa36-3800-11e8-8c42-66b4ba91c5e8.PNG)

**Comment by monte-crypto** [comment]
So many people have reported the same issue! Why are you guys not giving us a solution for this??

**Comment by LiamAird** [comment]
Join the discord for help: https://discord.gg/Er6UfJm
We do not offer supper through these issues. We use them as collection

**Comment by clownfish44** [comment]
@monte-crypto if you want PT v2 support then you must wait for an update. All of the hours of development are going into supporting PT v2.

**Comment by LiamAird** [comment]
Timezone offset should be fixed in the newest version, which will be released around the PT2.0 release.
