### ISSUE TITLE
Profit value calculation

### ISSUE THREAD

**Issue by CryptoLaz** [bTayFla/PtTracker#107]
How is Profit Value calculated? Is it the difference between Sold Value less Bought Cost? If so, the result of this calculation is not consistent.

**Comment by CryptoLaz** [comment]
The calculation of profit value in Sales Log isn't consistent (incorrect) making the profit reports unreliable... May I have an update on this please. Thank you.

**Comment by LiamAird** [comment]
Please search to see if an issue have been mentioned before.
#92

**Comment by CryptoLaz** [comment]
Thanks you.
