### ISSUE TITLE
[BUG] Missing transactions

### ISSUE THREAD

**Issue by bryanladd** [bTayFla/PtTracker#108]
Hi,

PtTrailer is selling coins yet Tracker is missing the transactions (not all of them).  Is there a way to rebuild the .db file and how do I avoid this in the future?  Running on Ubuntu 16.04 LTS

![binance_sales_p1](https://user-images.githubusercontent.com/38281140/38609506-1cc55fb4-3d33-11e8-9d99-cf266e9e6598.jpg)
![binance_sales_p2](https://user-images.githubusercontent.com/38281140/38609515-2049a6b8-3d33-11e8-8c25-61e4e46086a3.jpg)
![pt_tracker_saleslog](https://user-images.githubusercontent.com/38281140/38609520-2360f144-3d33-11e8-8aa7-9b1ce89456cb.jpg)

**Comment by clownfish44** [comment]
Use panic sell and it won't miss it. There is currently no way to do this

**Comment by bryanladd** [comment]
Panic sell will sell all the bags I have without profit.  Please explain.

**Comment by LiamAird** [comment]
Manuel sells are not recorded in Pt Tracker - we only monitor sells made by Profit Trailer.

**Comment by bryanladd** [comment]
@LiamAird I know Manual sales are not recorded in Tracker, these sells were made by the Trailer Bot
