### ISSUE TITLE
Balance, TCV etc all showing 0

### ISSUE THREAD

**Issue by razorseal** [bTayFla/PtTracker#111]
Hello. last version everything was working properly. Updated to 2.1 and now getting this. I have no updated PT to 2.0 yet. all my balances etc are at 0, and it appears the profit percentages are all off too

![image](https://user-images.githubusercontent.com/34427378/39078127-1a55b5f4-44d5-11e8-9d5a-bb3f3af34dbb.png)

**Comment by clownfish44** [comment]
Update to PT 2.0 and update PTT

**Comment by clownfish44** [comment]
Note: Not backwards compatible with ProfitTrailer v.1. Please update to latest ProfitTrailer before updating PtTracker.
