### ISSUE TITLE
pt v1.0 user use old license start pttracker 

### ISSUE THREAD

**Issue by cnmars** [bTayFla/PtTracker#112]
09:27:06 - info: Syncing data from ProfitTrailer
09:27:06 - info: Configuring server...
09:27:06 - error: There was a problem reading the PtTracker configuration file
09:27:06 - error: There was a problem reading the PtTracker configuration file:
09:27:09 - info: Checking license with key server...
09:27:09 - error: There was a problem validating the license with the key server
[root@xserver PtTracker]#

**Comment by clownfish44** [comment]
I strongly recommend moving to V2 with the latest PtTracker!

**Comment by clownfish44** [comment]
Please join the discord https://discord.gg/K9a37Vh

**Comment by tatarin38** [comment]
4|PTTracke | 2018-04-26 13:56 +00:00: 13:56:41 - info: Syncing data from ProfitTrailer
4|PTTracke | 2018-04-26 13:56 +00:00: 13:56:42 - info: Configuring server...
4|PTTracke | 2018-04-26 13:56 +00:00: 13:56:43 - error: There was a problem reading the PtTracker configuration file
4|PTTracke | 2018-04-26 13:56 +00:00: 13:56:43 - error: There was a problem reading the PtTracker configuration file:
4|PTTracke | 2018-04-26 13:56 +00:00: 13:56:47 - info: Checking license with key server...
4|PTTracke | 2018-04-26 13:56 +00:00: 13:56:53 - error: There was a problem validating the license with the key server

PT v 2.1.
