### ISSUE TITLE
[Feature] 24 hr volume in Coin Trends

### ISSUE THREAD

**Issue by NigglesSquiggles** [bTayFla/PtTracker#117]
Could you add under the Coin Trends data the 24hr volume for each coin? Also where are the TradingView icons and links to exchange?

**Comment by LiamAird** [comment]
Will look into it

**Comment by LiamAird** [comment]
24 hour volume will be added. 
What do you want the links to the exchange to be like? Same question for TradingView? 

They would need to be Coin / USD or Coin / EUR - It weren't added because it did not make much sense to add

**Comment by LiamAird** [comment]
Closed without answer for three days.
24 volume will be added.
