### ISSUE TITLE
DKK fiat currency wrong, and does not update

### ISSUE THREAD

**Issue by MarSkau** [bTayFla/PtTracker#120]
The DKK fiat currency shows with far too high a value as the latest, and only one historical value in the “BTC last hour” graph (closer to the correct value). The value seems to be updating once a day. In the image, the close prices are correct until the 24th, which is when I installed PtTracker.
![87946a5c-18aa-43db-a725-f233a0068cbd](https://user-images.githubusercontent.com/38716005/39230506-020c5a30-4867-11e8-83bb-14ed0badd783.jpeg)

**Comment by clownfish44** [comment]
https://github.com/bTayFla/PtTracker/issues/89
