### ISSUE TITLE
SQLITE_ERROR - When starting PtTracker

### ISSUE THREAD

**Issue by jamesbencke** [bTayFla/PtTracker#121]
I'm running ProfitTrailer on an AWS EC2 instance and when I try to run PtTracker, it throws a SQLITE_ERROR (see image).
![capture](https://user-images.githubusercontent.com/12985590/39245220-6df9dcd0-48d6-11e8-9cb3-db985127beb5.PNG)

If I start PtTracker while ProfitTrailer is running, PtTracker never starts and the SQLITE_ERROR is produced.
If I start PtTracker while ProfitTrailer is NOT running, PtTracker starts up but it can't login into ProfitTrailer (you can see those errors listed in the image attached). When I then start ProfitTrailer, the SQLITE_ERROR throws and PtTracker stops.

Am I doing something wrong?

**Comment by clownfish44** [comment]
1. Use pt v2 with the latest update.
2. Don't use AWS.
3. It will work!

**Comment by jamesbencke** [comment]
Thanks. 

It turns out that AWS is fine. It was my server name that had a special character that was causing the issue as per @clownfish44 response in #124.

All working now!
