### ISSUE TITLE
[Feature Request] Millitary Time (For EU users)

### ISSUE THREAD

**Issue by cryptogeek0610** [bTayFla/PtTracker#123]
I don't think this is too much work to feature in in the next update?

**Comment by propergol** [comment]
If you mean 10:00PM = 22:00, then I second that 👍

**Comment by yannickweijenberg** [comment]
Yes that’s what I mean. I still need to think twice when I see AM or PM whether it’s morning or in the evening

**Comment by LiamAird** [comment]
Coming to all you wonderful European people!

**Comment by LiamAird** [comment]
Added for next version.
