### ISSUE TITLE
Error: SQLITE_Error

### ISSUE THREAD

**Issue by dillonm1075** [bTayFla/PtTracker#124]
![error](https://user-images.githubusercontent.com/36042371/39272156-083db11c-48d3-11e8-9578-e47c152a3f98.jpg)

Anyone seen the error? I'm geting this on startup

**Comment by clownfish44** [comment]
Do a fresh setup again as to clear the database but first make sure the name of your profit trailer bot in PT under server sitename, and password has no special characters. Also make sure ptt has no special characters in the botname as well.
