### ISSUE TITLE
keep getting error pi installation

### ISSUE THREAD

**Issue by mimote85** [bTayFla/PtTracker#126]
![fehler](https://user-images.githubusercontent.com/38623709/39276592-01e6961e-48ea-11e8-8bdc-1b544c8e364d.PNG)

i did step by step the installation guide but keep getting this

**Comment by clownfish44** [comment]
Do a fresh setup again as to clear the database but first make sure the name of your profit trailer bot in PT under server sitename, and password has no special characters. Also make sure ptt has no special characters in the botname as well.

**Comment by mimote85** [comment]
thanks it works

and i also forget to do the last command

sudo ./PtTracker
