### ISSUE TITLE
Unsupported FIAT currency in PtTracker.json causes GUI to malfunction

### ISSUE THREAD

**Issue by techhitnz** [bTayFla/PtTracker#127]
E.g. Setting FiatCurrency to NZD or SGD will cause most of the GUI elements to disappear except for the charts.
![unknown](https://user-images.githubusercontent.com/32992068/39283783-085e0a5c-4964-11e8-97a2-50049076d647.png)

Setting back to "USD" resolves it.  When will additional fiat currencies be supported?

**Comment by clownfish44** [comment]
https://github.com/bTayFla/PtTracker/issues/89
