### ISSUE TITLE
Balance NaN ($0.00) TCV NaN ($0.00)

### ISSUE THREAD

**Issue by 2raj2raj** [bTayFla/PtTracker#130]
I have Tracker running against two instances of PT (v.1.2.6.23) and both of them have the issue. The issues displaying the balance and TCV, as Balance NaN ($0.00) TCV NaN ($0.00)

How do I fix this, please?

**Comment by clownfish44** [comment]
Please update to the latest pt as the latest tracker is only for pt v2 and up
