### ISSUE TITLE
Days not showing on Dashboard

### ISSUE THREAD

**Issue by Mannlig** [bTayFla/PtTracker#132]
![image](https://user-images.githubusercontent.com/33572431/39401759-92aeabc2-4b4d-11e8-8d6e-8fe20c9b54c3.png)

As shown in the image above you can see that the date 28. april is missing. 

I have this on two different installations on two different computers 
The image below is from another machine

![image](https://user-images.githubusercontent.com/33572431/39401773-119c2fc2-4b4e-11e8-8888-293cab80df67.png)

I have tried to restart both machines and booted up the tracker 2 times with no luck

**Comment by dorianbanks** [comment]
Known bug already reported.  Day only shows up when UTC hits midnight.

**Comment by LiamAird** [comment]
Should be fixed with the latest 2.1.1 version.
