### ISSUE TITLE
Two dashboard bugs (Profit Today and Daily Profit)

### ISSUE THREAD

**Issue by dorianbanks** [bTayFla/PtTracker#133]
1. "Profit today" only rolls over at UTC time, not server time.

2. Math is incorrect in "Daily Profit" section.

<img width="1356" alt="screen shot 2018-04-29 at 2 51 52 pm" src="https://user-images.githubusercontent.com/37125619/39411348-56b9d0fe-4bbd-11e8-8db1-840d306a802e.png">

**Comment by dorianbanks** [comment]
#1 is similar to issue #132.

**Comment by LiamAird** [comment]
Math seems correct to me. 
Highlighted days seems the same. 

days not shifting correctly is known and already reported.

**Comment by dorianbanks** [comment]
The math doesn't make sense....it is backwards.

April 30 - bought cost of 0.81641137 that sold for **less** at 0.80294123.  <----- this would make every trade a losing trade.

**Comment by LiamAird** [comment]
All right.. Was not what I was looking at. 
Will check
