### ISSUE TITLE
PtTracker is empty

### ISSUE THREAD

**Issue by turcane** [bTayFla/PtTracker#135]
PtTracker can connect to ProfitTrailer and gets at least data for "Current Value Distribution" but rest of PtTracker is empty/blank.
Browser console is full of errors.

6|[PTTrack | 2018-05-01 14:53 +02:00: 14:53:18 - info: Syncing data from ProfitTrailer
6|[PTTrack | 2018-05-01 14:53 +02:00: 14:53:33 - info: Syncing data from ProfitTrailer
6|[PTTrack | 2018-05-01 14:53 +02:00: 14:53:48 - info: Syncing data from ProfitTrailer
6|[PTTrack | 2018-05-01 14:54 +02:00: 14:54:00 - info: Updating market data for BTC
6|[PTTrack | 2018-05-01 14:54 +02:00: 14:54:03 - info: Syncing data from ProfitTrailer
6|[PTTrack | 2018-05-01 14:54 +02:00: 14:54:18 - info: Syncing data from ProfitTrailer
6|[PTTrack | 2018-05-01 14:54 +02:00: 14:54:33 - info: Syncing data from ProfitTrailer
6|[PTTrack | 2018-05-01 14:54 +02:00: 14:54:48 - info: Syncing data from ProfitTrailer
6|[PTTrack | 2018-05-01 14:55 +02:00: 14:55:00 - info: Updating market data for BTC
6|[PTTrack | 2018-05-01 14:55 +02:00: 14:55:03 - info: Syncing data from ProfitTrailer
6|[PTTrack | 2018-05-01 14:55 +02:00: 14:55:18 - info: Syncing data from ProfitTrailer
6|[PTTrack | 2018-05-01 14:55 +02:00: 14:55:33 - info: Syncing data from ProfitTrailer
6|[PTTrack | 2018-05-01 14:55 +02:00: 14:55:48 - info: Syncing data from ProfitTrailer
6|[PTTrack | 2018-05-01 14:56 +02:00: 14:56:00 - info: Updating market data for BTC
6|[PTTrack | 2018-05-01 14:56 +02:00: 14:56:03 - info: Syncing data from ProfitTrailer

[log.txt](https://github.com/bTayFla/PtTracker/files/1963806/log.txt)

domain replaced by domain.tld
OS: Ubuntu 16.04 LTS
PT: 2.0.1

<img width="1665" alt="bildschirmfoto 2018-05-01 um 14 00 05" src="https://user-images.githubusercontent.com/9463106/39473656-2a0febf8-4d50-11e8-98a0-0dc2459b7a3f.png">

running for more than 24 hours with a lot of buys/sells on PT

**Comment by clownfish44** [comment]
Please join the discord https://discord.gg/K9a37Vh for support, also those are not errors in console that is what it is supposed to say.

**Comment by turcane** [comment]
I tried discord but they could not help me.

**Comment by clownfish44** [comment]
@JediWed what is your discord name?

**Comment by turcane** [comment]
Wed
