### ISSUE TITLE
Bought cost higher than sold cost, but have profit

### ISSUE THREAD

**Issue by riggermortum** [bTayFla/PtTracker#136]
It seems the sales log info in Tracker is showing an bought cost was higher than a sales cost, but showing profit.  PT showing correct info for all.  Look at the middle sale, has a profit, but sold cast is a lot lower than bought.

![trackereth](https://user-images.githubusercontent.com/35870508/39479975-bece5032-4d5e-11e8-8eca-a44331d45beb.JPG)

**Comment by LiamAird** [comment]
Can you screenshot the same three entries from ProfitTrailer?

**Comment by dorianbanks** [comment]
Same as #133

**Comment by riggermortum** [comment]
![capture](https://user-images.githubusercontent.com/35870508/39677184-9348014c-516e-11e8-97af-ce3561e1986c.PNG)

**Comment by riggermortum** [comment]
Other examples of inaccurate reporting of profit with bought/sold costs.  Why are the figures so different to trailer?

![onttracker](https://user-images.githubusercontent.com/35870508/40541114-62c51f48-6012-11e8-96c5-2a2a059c454c.JPG)

![onttrailer](https://user-images.githubusercontent.com/35870508/40541118-66550d3a-6012-11e8-8014-dc9db76d661f.JPG)

**Comment by LiamAird** [comment]
Should be fixed in next release.
