### ISSUE TITLE
[ISSUE] MACD buy strategy Trigger displays different to Sell strategy Trigger

### ISSUE THREAD

**Issue by NigglesSquiggles** [bTayFla/PtTracker#146]
![capture](https://user-images.githubusercontent.com/36387929/40153052-498bd8de-59cb-11e8-933c-ab38823b903d.JPG)
In the log pages, MACD buy strategy Trigger values are displayed as scientific notation, whereas the Sell strategy Triggers are displayed to the 9th decimal. Could BOTH be displayed as 9 decimal places?

**Comment by LiamAird** [comment]
Will be fixed in the next release
