### ISSUE TITLE
Trend change sorting doesn't work correct on negative values

### ISSUE THREAD

**Issue by cryptt** [bTayFla/PtTracker#147]
As title explains already when sorting the trend change the negative values won't sort correctly.
On positive percentages it goes from the biggest (green) change to the least correctly but then the red numbers show not the next step which should be 0.00% but it will start with the biggest red number and from there up to 0.00% as the last.
![image](https://user-images.githubusercontent.com/34436021/40265362-0e88267e-5b61-11e8-8480-673ee4b0091c.png)
Example above the first red number after the green should be -1.23% and the last -4.79% (assuming -4.79% is the last entry)
![image](https://user-images.githubusercontent.com/34436021/40265371-3345011c-5b61-11e8-97d4-d2c023842805.png)
As you can see here it should start with -8.23% going down to -0.40% and then starting with the green numbers

**Comment by LiamAird** [comment]
Corrected for next version
