### ISSUE TITLE
Dust Value wrong

### ISSUE THREAD

**Issue by DanielRuppen** [bTayFla/PtTracker#148]
I run PT 2.0.7 on Binance with Tracker 2.1, all works well except Dust log isn't

PT Dust Log Summary:
Current Value	0.00219200 (CHF18.16)
Difference	(-2.53 %) -0.00005698 (CHF-0.47)
Bought Cost	0.00224897 (CHF18.64)

PT Tracker Dust summary:

Category | Pairs | Cost | Value | Profit
Dust | 91 | 1.8099490 ($15,038.61) | 0.0021921 ($18.21) | -6.87% (-$15,020.40)

**Comment by LiamAird** [comment]
This is an issues with PTs latest versions. 
It has been fixed in PT 2.1 versions, which is yet to be released.
