### ISSUE TITLE
Tradingview chart time /date not alighned with true value 

### ISSUE THREAD

**Issue by cryptomail2018** [bTayFla/PtTracker#149]
second time i request help on this issue please 

why is the DATE/TIME of chart on trading view in PT TRACKER not alighned with true value is there a way to add a code somehow to adjust this as it is reading the information of PT Trailer but not this data neither that of  TRADINGVIEW . 

please advice on this

**Comment by cryptomail2018** [comment]
yes i send again with screenshot , but its closed now and whats the verdict ?

**Comment by LiamAird** [comment]
Has then been correct with the timezone correction of the version 2.1.1?

**Comment by LiamAird** [comment]
No answer, will close.
If this continues to be an issue please re-open.
