### ISSUE TITLE
V 2.1.1 in windows when updated Pt Tracker CMD not starting 

### ISSUE THREAD

**Issue by cryptomail2018** [bTayFla/PtTracker#152]
new version not starting in windows

**Comment by clownfish44** [comment]
Right click on the exe file then go to properties and unblock it then apply and close. If you have more trouble please join the official discord for support! https://discord.gg/K9a37Vh

**Comment by LiamAird** [comment]
Did you add the newest addition to the config? 
Its explained on the release page.
