### ISSUE TITLE
V2.1.1 the TV chart time in PT Tracker Pairs GUI is not following Time as set 

### ISSUE THREAD

**Issue by cryptomail2018** [bTayFla/PtTracker#154]
please see attached screenshot where you can see the time of the TV in the GUI in Pairs for instance is not lining up with time of local area , can this please be adjusted or allow the PT Tracker to follow our own settings in TV on this with a Account link 
![capture](https://user-images.githubusercontent.com/35930742/40760884-12e6fe50-64c3-11e8-81f5-17e708d9fdbc.PNG)

**Comment by clownfish44** [comment]
#149 duplicate
