### ISSUE TITLE
2.1.1 Raspberry Pi release missing

### ISSUE THREAD

**Issue by techhitnz** [bTayFla/PtTracker#155]
Will this release be coming out for the Raspberry Pi soon?

**Comment by determo13** [comment]
Waiting for release 2.1.1 too!!! armv7 please!

**Comment by XxxSpiritvsxxX** [comment]
No love for Raspberry Pi anymore?

**Comment by propergol** [comment]
no love for developping/working, thats much simpler

**Comment by LiamAird** [comment]
We will see what we can do for next release, that we are testing right now.

**Comment by LiamAird** [comment]
Pi releases will not happen any longer. 
We will not support them.
