### ISSUE TITLE
[Enhancement] Screen Keyboard for Login

### ISSUE THREAD

**Issue by RchGrav** [bTayFla/PtTracker#157]
Could you possibly add this (or some) screen keyboard for entering the password.
I want to use PTT in a way which does not allow keyboard input but does allow mouse clicks.
I found a real nice project that appears very straight forward to implement and solid.
https://github.com/Mottie/Keyboard 
DEMO -> https://mottie.github.io/Keyboard/
Thanks!

**Comment by LiamAird** [comment]
Such a feature is not planned in the current state of the app.
Will archive it
