### ISSUE TITLE
Counting multiple DCA buy on a single buy

### ISSUE THREAD

**Issue by FerHen1981** [bTayFla/PtTracker#159]
In DCA log it shows multiple buys although there has been only a single buy.

**Comment by LiamAird** [comment]
Please share screenshots of the issue, so that we can check it out. 
Also a screenshot of how PT is showing it.

**Comment by FerHen1981** [comment]
[
![schermafdruk 2018-07-03 01 43 00](https://user-images.githubusercontent.com/37780411/42191337-a249b80e-7e62-11e8-9215-1ce0c9353faf.png)
](url)

**Comment by FerHen1981** [comment]
![schermafdruk 2018-07-03 01 43 00](https://user-images.githubusercontent.com/37780411/42191346-afb301c6-7e62-11e8-922d-722dffabcfbe.png)

**Comment by FerHen1981** [comment]
This is just only one buy
![schermafdruk 2018-07-03 01 46 19](https://user-images.githubusercontent.com/37780411/42191377-eaebfeaa-7e62-11e8-8a47-ee4d42d5c05c.png)

**Comment by FerHen1981** [comment]
I’ve done that. Hope to here from you soon

Kind regards,
Ferry

Op 3 jul. 2018, om 01:15 heeft Liam Aird <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Please share screenshots of the issue, so that we can check it out.
Also a screenshot of how PT is showing it.

**Comment by FerHen1981** [comment]
I am running PT Feeder (so you know)

**Comment by FerHen1981** [comment]
PT Feeder, PT Notifications, PT Tracker and PT Defender

**Comment by FerHen1981** [comment]
And i'm buying on Gnome Alerts PRO

**Comment by LiamAird** [comment]
This is because the DCA level will only be nulled whenever PT buys a new instance of that coin again. 
If you buy with Gnome Alerts the old DCA level sign will always be there. 

You can reset it through PTs hotconfig with GAS_DCA_set_buy_times = 0
https://wiki.profittrailer.com/doku.php?id=hotconfig
