### ISSUE TITLE
zero dev progress since months! What's happening?!

### ISSUE THREAD

**Issue by propergol** [bTayFla/PtTracker#161]
Can you explain how this paid project has such low developement frequency?

You have now enough money, and dont care about huge bugs reported more than 3 month agao now?

Seriously I dont care to listen to your anwser.

I will just start spreading infos on how you are a lasy dev.

**Comment by LiamAird** [comment]
If you have not noticed we have just closed a bunch of issues and commented on several others.
We do not implement or respond to every issue on here.

You can always find us in the tracker channel on the PT discord.
We are working on releasing version 2.2, which bring new features and bugfixes.

AS this is not an issue it will be closed with this message.
