### ISSUE TITLE
v2.2 web access login no longer function - data is not protected from internet access! 

### ISSUE THREAD

**Issue by kkkoay** [bTayFla/PtTracker#164]
The login screen used to function till version v2.1.1 and in v2.2 it is no longer function. Now when accessing the URL, it went straight through to the dashboard without even a login screen. If accessing the login page http://somedomainname.com:1234/#/login I got a empty screen. 

It is vital to have a login screen to allow remote access to PtTracker. Otherwise everyone else can access the system without any login and all my data is exposed to the internet.

Due to this issue, now I have to disable internet access to the system. Please help to turn on or fix the login feature again.

**Comment by ilmarioranen** [comment]
How can such an obvious issue stay unaddressed here for over 20 days?

The current PTTracker exposes the dashboard to the world without any kind of login! That makes this plugin totally unsecure and unuseable. 

How about fixing this as a 1. priority before doing anything else?

**Comment by LiamAird** [comment]
Added - Check the releases page
