### ISSUE TITLE
Missing ARM version

### ISSUE THREAD

**Issue by radeksalomon** [bTayFla/PtTracker#165]
Hello,

when do you release ARM version? This tool is the official part of ProfitTrailer but we cannot use it on ARM devices right now or we have to use old version.

Thanks for releasing it asap.
Radek

**Comment by radeksalomon** [comment]
Your statement on the website is not exactly true right now.

Is my setup supported?
Yes, PtTracker will work on any operating system that ProfitTrailer supports.

**Comment by XxxSpiritvsxxX** [comment]
They don't support it anymore on ARM.
There goes the money I paid for this out the window.
I can't use it anymore on my platform. Stuck with an old version forever now.

Wish I could get refunded. Would never buy this if I knew Raspberry Pi support would be dropped.

**Comment by UWillC** [comment]
Just give a hint how to compile the code for Pi at least.

**Comment by radeksalomon** [comment]
They support all version on which PT can run. So they support also ARM. It is official add-on for PT Pro, so it must work with every PT instance.
