### ISSUE TITLE
error while loading shared libraries: .6

### ISSUE THREAD

**Issue by ftwmining** [bTayFla/PtTracker#168]
when I try to run it always says this.

/var/opt/pt/PtTracker/PtTracker: error while loading shared libraries: .6: cannot open shared object file: No such file or directory

<img width="1060" alt="pt tracker" src="https://user-images.githubusercontent.com/42490724/44297988-605d6280-a2a0-11e8-90f0-9bc17dbe6ea7.png">

**Comment by LiamAird** [comment]
It seems like the user is missing rights from executing the application.

Please join our discord, located the Tracker-support channel and we will try to guide you.
https://discord.gg/CZJqkke

**Comment by ftwmining** [comment]
Im already on Discord, but I dont see any #Tracker-support Chanel on PT, under support tab is only #pre-purchase

**Comment by LiamAird** [comment]
You need to activate your license, via the pt assistant bot.
You can ask for advice to activate in the pre-purchase channel too. When you are activated you will be able to see the other channels.
