### ISSUE TITLE
[Feature Request] Option to open up in Tradingview.com

### ISSUE THREAD

**Issue by Tornado-Truxton** [bTayFla/PtTracker#17]
When one clicks on a coin name  X give the option to open up in trading view : 

X = GTOETH 

For example, I click on X coin from DCA, Pairs or Daily section and a link opens up in a new tab to : 

https://www.tradingview.com/symbols/GTOETH/ 

Is configurable so if others want a different lookup URL you don't need to touch your code : 

  "General": {
	"CoinLookURL": "https://www.tradingview.com/symbols/%X%/"
  }

**Comment by clownfish44** [comment]
Added
