### ISSUE TITLE
APPCBTC price is wrong in the PT

### ISSUE THREAD

**Issue by Devir71** [bTayFla/PtTracker#170]
I just noticed that price of the APPCBTC pair is way off in PT.

Current price is 0.00001917 BTC and PT shows 0.00001332 BTC.

![image](https://user-images.githubusercontent.com/17989456/44325536-10f56e80-a427-11e8-80f8-27bc0770efb5.png)

**Comment by LiamAird** [comment]
We need more information than this.
You reported this is from PT, but you have written it in the PtTracker github page. 

Please join the discord server to get help sorting this out: https://discord.gg/t6Zk5S
