### ISSUE TITLE
after update - no more asking for password

### ISSUE THREAD

**Issue by F1shst4le** [bTayFla/PtTracker#171]
Hello, i updated to the newest version but now PTTracker does not ask for any password anymore
also the webpassword= "" is missing in the PTTracker.json file 

also adding the line webpassword = "abc123" does not help 

how can i add the password option again?

**Comment by ilmarioranen** [comment]
Is this project abandoned? 

How can such an obvious huge security issue stay unaddressed here for over a month??

**Comment by LiamAird** [comment]
Added - Check the releases page
