### ISSUE TITLE
[bug] PTTracker v2.2.1 two instances use a lot of RAM

### ISSUE THREAD

**Issue by des1re10** [bTayFla/PtTracker#176]
Im running two bots on one windows server. One PTTracker process claims plenty of ram. Is that a bug or wanted? I have 8GB overall.

I have considered to use different ports and API token ofc. The software itself just works fine.
![screenshot 2018-11-13 02 01 49](https://user-images.githubusercontent.com/11975743/48384171-67eaa700-e6e9-11e8-82da-880562f96b5e.png)

**Comment by LiamAird** [comment]
Please join the PT discord and find us in the tracker-support channel. 
We will better be able to support you and figure out the cause.
