### ISSUE TITLE
Pending Value is not correct

### ISSUE THREAD

**Issue by MagicLazy** [bTayFla/PtTracker#177]
I have 2 PT bots running. One of them is in testmode. The TCV value is only calculated and displaced correctly on the test Bot. 

From my understanding the TCV should be the following sum:
TCV = Balance + Pairs Value + DCA Value + Pending Value + Dust Value

On the live Bot the displayed TCV is not correct and is too high.

**Comment by MagicLazy** [comment]
I noticed also that the Pending value in PT tracker is not the same as in ProfitTrailer when the bot is live.

**Comment by MagicLazy** [comment]
So TCV is correct as in Profit Trailer. The only mistake is the Pending Value which is not the same as in Profit Trailer when the bot is live. When the bot is papertrading then it is correct.

**Comment by LiamAird** [comment]
Can you share screenshots of the issue you are having?
Which version of tracker are you running?

**Comment by MagicLazy** [comment]
PT Tracker 2.2.1. 
Profit Trailer 2.1.28.
![image](https://user-images.githubusercontent.com/38259749/50987987-6d0e7b80-150b-11e9-9172-86de369d0c6a.png)
![image](https://user-images.githubusercontent.com/38259749/50988027-97603900-150b-11e9-9966-3f960981b5ef.png)

**Comment by LiamAird** [comment]
Please join the discord server and get a hold of the support team - it'll be easier to help in there: https://discord.gg/yXzzs3

**Comment by MagicLazy** [comment]
Ok thanks

**Comment by LiamAird** [comment]
Issue resolved on discord
