### ISSUE TITLE
doubling bought coins?

### ISSUE THREAD

**Issue by Cronos44** [bTayFla/PtTracker#178]
hi, i recently updated to 2.2.2 and it seems to have doubled all my bought coins? any idea whats happened? thanks

**Comment by LiamAird** [comment]
We are aware of the issue and are working on a fix for this
You can use a DB browser for sqlite to remove the doubled pairs, or delete and re-fetch the values for your tracker.

**Comment by Cronos44** [comment]
how would i go about re fetching the information from profit trailer? would i delete and reinstall pt tracker? thanks

**Comment by LiamAird** [comment]
You can simple delete / rename the db file of Tracker and it will create a new one with new data.

**Comment by Cronos44** [comment]
thanks for fast reply! just tried but it is still the same.

**Comment by LiamAird** [comment]
This should be fixed with the latest release, when fetching new data.

**Comment by Ronanza** [comment]
Hi @LiamAird 

I'm having a similar issue with db entries in the "sells_log" table. Every time I start PTTracker the number of entries doubles. If I use a db browser to the delete the new records, they will be created again on next startup of PTTracker.

It appears that most (all?) Sales are now logged twice, One record for my local time (CET) and another for UTC - see screenshot

I'm using PTT v2.2.5 and PT 2.2.12 - just upgraded both from PT 2.1.30 and PTT v2.2 respectively.

Deleting the db file works as a workaround. However, by doing so I'll lose all trading history >7 months. So this is not an option for me. Please support. Thanks!

![shot](https://user-images.githubusercontent.com/38175606/54500154-0eee8200-491a-11e9-939d-9b0655c8fac1.png)

**Comment by LiamAird** [comment]
@Ronanza Please join the PT discord and we can see what we can do about it.
https://discord.gg/Tmqcd7
