### ISSUE TITLE
PtTracker Clock and Order list times 

### ISSUE THREAD

**Issue by cryptomail2018** [bTayFla/PtTracker#181]
how can this be alighned with Area i reside at it is out by 5 hours behind on clock

like a timezone setting to get all data lined up with local times 
including the charts

**Comment by LiamAird** [comment]
Please join the PT discord for such issues:
https://discord.gg/Tmqcd7

**Comment by cryptomail2018** [comment]
your link aint working and several other have asked you the same questions and no answer as just yet .. this was always been a issue to be honest i asked many times and never got sorter out TBH

with kind regards

Crypto Skimmerhttps://www.facebook.com/crypto.skimmer.1

 

    On Friday, 29 March 2019, 4:19:59 pm GMT+7, Liam Aird <notifications@github.com> wrote:  
 
 
Please join the PT discord for such issues:
https://discord.gg/Tmqcd7

**Comment by LiamAird** [comment]
Here is a new invite link: https://discord.gg/yVrfYzX
People have had their issues resolved where support is offered, which is the official pt discord. 

If you have not updated to the latest version, please do so to, as we resolved the offset time in the latest releases. 
You can get further support in the official pt discord server.
