### ISSUE TITLE
Could not fetch data from ProfitTrailer

### ISSUE THREAD

**Issue by tgbrfvedcs** [bTayFla/PtTracker#182]
I was running ProfitTrailer on a VPS, but I failed to run the PtTracker with if.
I have follow the guide to set it up, and it failed at the end, the error was sow in the following

0|PTTracker  | 2019-04-08 03:26 +00:00: 03:26:35 - info: Success! License has been verified
0|PTTracker  | 2019-04-08 03:26 +00:00: 03:26:35 - info: Starting PtTracker server...
0|PTTracker  | 2019-04-08 03:26 +00:00: 03:26:35 - info: Success! PtTracker is running at http://localhost:3091
0|PTTracker  | 2019-04-08 03:26 +00:00: 03:26:35 - info: Updating market data for undefined
**0|PTTracker  | 2019-04-08 03:26 +00:00: 03:26:36 - error: There was a problem fetching coin minute candle data for undefined
0|PTTracker         | 2019-04-08 03:28 +00:00: 03:28:21 - error: Could not fetch data from ProfitTrailer**

what would be the problem of it? thanks!!

**Comment by LiamAird** [comment]
One error could be a wrong URL for PT or wrong ApiToken.
Also make sure you have the newest version.

For faster and more indepth support, please join the official PT discord.
https://discord.gg/yVrfYzX
