### ISSUE TITLE
error: Token did not match for Dust

### ISSUE THREAD

**Issue by nicknack1** [bTayFla/PtTracker#183]
error: Token did not match for Dust
error: Token did not match for Minute Candles
error: Token did not match for Profitable-Pairs
error: Token did not match for Sales
error: Token did not match DCA
error: Token did not match Pending

**Comment by LiamAird** [comment]
Please read the upgrade instructions. 

Clear your browsers cache and cookies
Log in to your PtTracker again.

**Comment by LiamAird** [comment]
If you still have errors, please join the official PT discord and get support: https://discord.gg/yVrfYzX
