### ISSUE TITLE
must use private navigation since 2.2.6 otherwise nothing load

### ISSUE THREAD

**Issue by propergol** [bTayFla/PtTracker#184]
since the latest 2.2.6, I cant use standard browser tab and must use private navigation otherwise page doesnt refresh display values.

**Comment by propergol** [comment]
mhh, weird : I clean again my cache and now it has correctly updated datas from PT.

**Comment by LiamAird** [comment]
Good to know you got it working. 
Tried to ping you on the PT discord - Please write in the support channel, if you have issues.
