### ISSUE TITLE
[Feature Request] Support For Other Fiat Currencies

### ISSUE THREAD

**Issue by smoochy** [bTayFla/PtTracker#2]
Hi there :)
For all non US folks it would be very beneficial to be able to select another Fiat currency like EUR etc. 
Prices of trades etc should be converted according to the selected currency.

**Comment by tooraj-enayati** [comment]
I'd be interested in AUD.

**Comment by clownfish44** [comment]
added

**Comment by clownfish44** [comment]
Implemented in V2 :D
