### ISSUE TITLE
 [Feature Request] Need To Update Notification

### ISSUE THREAD

**Issue by GLock-PPC** [bTayFla/PtTracker#20]
Would be useful to show when the data in the tracker has been last updated, in case we have stuck crontab or scripts etc...

It is important to show when the actual data is valid.

**Comment by clownfish44** [comment]
A way to have the gui tell you that it needs an update all over it would be a very nice feature

**Comment by clownfish44** [comment]
added

**Comment by clownfish44** [comment]
Implemented in V2 :D
