### ISSUE TITLE
[Feature Request] More Data Analysis

### ISSUE THREAD

**Issue by iller75** [bTayFla/PtTracker#22]
It would be great if we could get more data analysis. 

What i would like to see would be analysis of best performing coins, how many buys and sells i get on each pair and how many dca's each pair get. With this i could better understand what coin might dca more than others and also see if that brings more profit or if i should remove that pair from trading. Would also be good to know how long one holds each coin for on average. 

A bit like this sheet does https://www.youtube.com/watch?v=AKzp6H118co

**Comment by clownfish44** [comment]
Hello, I love this suggestion and we will be working on adding these very soon!

**Comment by CousinEddie** [comment]
Ditto, clownfish! I just watched the video and those are some nice features. Makes me wish I had my coding skills up to par to be able to help.
