### ISSUE TITLE
[issue] error validating

### ISSUE THREAD

**Issue by woodyalien** [bTayFla/PtTracker#27]
For days already I am getting this message on the browser right after starting PTT:
"Error Validating. Please close and try again in 5 minutes (do not keep refreshing). If the problem persists, your license key may be already in use on another machine."
It doesn't matter how long I wait and I am not using any other VPS for PT*; killing process or even rebooting does not help anything.

**Comment by briersben** [comment]
I am having the same issue!

**Comment by clownfish44** [comment]
Read the wiki! If you need further help please join the discord which is linked in the wiki!
