### ISSUE TITLE
[Feature Request] Add alt coins to transfers

### ISSUE THREAD

**Issue by armcbride12** [bTayFla/PtTracker#28]
I've deposited more than just BTC to my exchange account from other exchanges, so it would be nice if I could specify other coin deposits like the ETH coins I transferred on 2-2-18 without having to look up historical BTC to ETH in the past so that my transfers reflect correctly.

**Comment by clownfish44** [comment]
will you be selling these coins for your base currency or just a hold?

**Comment by armcbride12** [comment]
@clownfish44 At some point in the near future I will sell my ETH holdings for BTC .

**Comment by clownfish44** [comment]
Once you sell just set as a deposit to base currency

**Comment by armcbride12** [comment]
Setting the sell as a deposit in base currency is fine for 1-3 currencies, but if you've transferred 20 alts to the exchange your bot is running on - it becomes very tedious to adjust base currency deposits each time you close out 1 of those 20 alts.
