### ISSUE TITLE
[Feature Request] Increase to 8 digits for shown numbers

### ISSUE THREAD

**Issue by smoochy** [bTayFla/PtTracker#29]
Hi there,

I think it will be an improvement, if you could increase the number of used digits.

For instance yesterday I made a profit of 0.00139672 according to PT. But PTT only translates this to 0.001400 which is very inaccurate. 

It would be better, if PTT would display 8 digits after the point everywhere.

If needed, PTT could use the browser display weight much more, as at the moment on the right and left side of the tables is a lot of unused space.

Thanks.

**Comment by clownfish44** [comment]
Improved in next update
