### ISSUE TITLE
Json file wiped clean!!!

### ISSUE THREAD

**Issue by cloudmininggroup** [bTayFla/PtTracker#3]
So I just purchased and instaled the ProfitTrailer Tacker, after watching thre you tube video and although it looks promising when launched it showed only one trade? I had my saved trade days set to 90 previously and the log file is huge but the Tracker Wiped my entire json history at lunach!! Log file is till there but the bot thinks its brand new! Any thoughts.... let my now lack of all trading history in the json file be a warning!!!

**Comment by smoochy** [comment]
Did not happen to my setup I just did 15 minutes ago. So should be a specific issue to your configuration, not a general one. For which more information from your side is needed.

**Comment by smoochy** [comment]
I had just the same issue 20 minutes ago.

PT sales log was empty, only the last sale was in there. I stopped PTT, stopped PT, copied back a backup sales log file and started only PT again. I had my 206 sales back, except for the last one.

A few minutes later, with the next sale, the sales log again got emptied. Only the most recent sale was populated.
I am not sure, but I think this is more related to PT than to PTT

**Comment by smoochy** [comment]
I think I figured out, how this happened: I set trading.logHistory = 9999999999999999.

According to taniman (PT dev) 

> that value will cause an overload and will effectively make the value 0.

This will cause to wipe Sales Log, as you set to not have any trading history.

**Comment by woodyalien** [comment]
so what is the biggest acceptable value in that field?
anyway should we expect longer period than 9999 days? would that be valid?

**Comment by smoochy** [comment]
See his answer here:

9999 would be valid.

**Comment by woodyalien** [comment]
Perfect then, that means 20+ years!
I think PTT team just needs to update their manuals them... and problem solved  :)

**Comment by clownfish44** [comment]
Solved set it to 365
