### ISSUE TITLE
[Feature Req] Make PTT access password protected

### ISSUE THREAD

**Issue by smoochy** [bTayFla/PtTracker#4]
Hi,

I've setup PTT on my VPS and it is running. I've changed the default port in mongoose.conf to sth different. I can access PTT via http://[IPofVPS]:[Port]/. Unfortunately there is no password protection. This means, everybody who scanned the IP address and used ports of the VPS can access my statistics.

I think this is a security risk which could be prevented by setting a password protection like PT has.

**Comment by clownfish44** [comment]
You can set a password on all distro's of Linux as seen in the install link. It also recommends that you keep the port closed however for windows and mac if you want to open the port you can set it to only allow certain ip's to access it. https://github.com/bTayFla/PtTracker/blob/master/README.md

**Comment by smoochy** [comment]
I am not using a Linux VPS so telling me to use one is not a solution.

The readme is not describing how to setup your mentioned "open the port you can set it to only allow certain ip's to access it" method.

In addition only allowing certain IP address to access it is not a feasible solution. Neither home computers nor mobile phones do have static IP addresses.

So adding a simple password protection when accessing PTT should suite most of the users.

Thank you.

**Comment by woodyalien** [comment]
@clownfish44 and PTT team: I must say that I support @smoochy 
I am exactly on the same situation he described.
I would definitely agree that this is not top priority, but would be nice to see something in that direction.

**Comment by smoochy** [comment]
Thank you very much for adding the authenticating to the new version. Very much appreciated!

**Comment by woodyalien** [comment]
the solution is appreciated, thanks!
