### ISSUE TITLE
[Feature Request] API Use To Import Trade Data From Exchange

### ISSUE THREAD

**Issue by vskbs** [bTayFla/PtTracker#47]
Is it possible to import the trade history from Binance to consolidate the manual selling.
As PT does not track manual selling, it would be a great value addition if PT tracker allows Trade history imports from Binance or API links to Binance.? is it in development?
 It would be a great value if this is available as  many trades are done manually by most of the people and we need to consolidate  those trades for many purposes including tax, 

Please update on this request.

Thanks

**Comment by timt200** [comment]
Fantastic idea!!!!
At present PT Tracker is next to useless without this.
This request is a must do feature and should of been done from day one.

**Comment by vskbs** [comment]
Yes. Right now only option for Binance or Exchange API imports is to go to monthly subscription of coin tracking. If this is available in PT tracker, it will be a great value for the One time cost of PT tracker purchase and it will help all types of manual trading customers as well..

**Comment by LiamAird** [comment]
Will the cooperation between PT and PTT, there is no planned exchange support. 
Archived.
