### ISSUE TITLE
[NEW FEATURE] multi-bot dashboard

### ISSUE THREAD

**Issue by woodyalien** [bTayFla/PtTracker#5]
As we spoke, I appreciate that you are open for suggestions and new ideas for development!
And following our conversation, I would like to have a multi-bot dashboard while still allowing to go into details of each bot if wanted.
Thank you!

**Comment by woodyalien** [comment]
@clownfish44 why simply closed?! can you please comment?

**Comment by woodyalien** [comment]
@clownfish44 ?

**Comment by clownfish44** [comment]
Just run two instances. Until PT has a multi bot dashboard we won't.

**Comment by woodyalien** [comment]
@clownfish44 sorry but this is not a reasonable conclusion.
PT is a trading tool: a universal dashboard can be built but cannot be expected, it is not PT's focus;
PTT is a tracking and reporting tool: it makes all sense in this context, perfect aligned with your product.

I do not see PT ever having a multi-bot dashboard (though technically possible);
Does not make sense for PTT to expect PT to do it first.

Also you know that we have exchanged the email below PRIOR to my order and to this record. Just a copy/paste below:
_Feb 13, 2018 at 8:48 AM, from myself
Hello guys, very interesting product that makes our lives easier - congratulations! Question: is this a product that you plan to keep developing or it is supposed to be as-is? Even though already enjoying the status quo, there are features that I would like to see, and the most complex one would be: - a single dashboard for all 3 bots I run, I would like to see a consolidated view of all 3, and going to the individuals if willing to navigate thru details. So, is this kind of development something you would consider or changes should be out of my expectations? thanks! 

Feb 13, 2018 at 3:51 PM, Pt Tracker <pttrackerinfo@gmail.com> wrote:
Hey woody, Love the ideas! We are actively developing and updating PtTracker, watch for new multibot functions in the future :)

Feb 13, 2018 at 4:38 PM, myself again:
Excellent, thank you!
In that case, in support of what comes, I will get a license now..._  


Regardless our messages exchanged, please reconsider, this would be an amazing feature and I am not aware of any other competitor offering such!   (and maybe that is why you changed your mind and not anymore willing to do it, but that is how innovation comes up!)
