### ISSUE TITLE
[Feature Request] Historic Trades

### ISSUE THREAD

**Issue by harrywh** [bTayFla/PtTracker#55]
Need to be able to show all trade history from the exchange.
And not be limited by the last so many days logged by Profit Trailer.
This application should be independent from Profit Trailer.

Data from the exchange should only be downloaded locally on a schedule. For example once every hour or once every day. To minimize the number of requests avoiding the possibility of being ban from the exchange and stopping unnecessary calls to the exchange being made.
If to display more than say the last six months worth of data is too much to handle. Than an archive feature would be required. This would mean the user would then required a filter selection so that they could view previous months of trade.

Month on month trade comparison would be handy.
All screens should be able to be converted to user chosen Fiat currency.
Simpler way to start PT Tracker without the need for mongoose.

**Comment by clownfish44** [comment]
https://github.com/bTayFla/PtTracker/issues/47

**Comment by d4260** [comment]
How do you import historic data?
