### ISSUE TITLE
[Bug] Monetary symbol Does Not Change

### ISSUE THREAD

**Issue by CryptoSpidey** [bTayFla/PtTracker#59]
Hi, 

Very nice update v2.0 completely transformed PTTracker. 

I add "FiatCurrency": "INR". Thought figures are right with INR but it still USD $ monetary symbol what I need rupee ₹ symbol (HTML code &#8377;. Hope you will update this in next version.

**Comment by clownfish44** [comment]
No issue found you must restart your PtTracker in order for it to work. If it still shows USD you need to clear your browser cache. If nothing else hop in our discord.
