### ISSUE TITLE
[Feature Request] Encrypt PT Password

### ISSUE THREAD

**Issue by smoochy** [bTayFla/PtTracker#60]
Dear PTT Team,

first of all I would like to thank you for that awesome update to PTT.

I want to bring up a topic, I already opened with PT in the past(https://github.com/taniman/profit-trailer/issues/1361), and thankfully they could find a way to store the PT webgui password in an encrypted way.

Unfortunately PTT stores the PT password in plaintext in its .json file.

Wouldn't it be better, if either PTT would also save the password in an encrypted way, or even better, would access the ptpw file from PT directly?

**Comment by smoochy** [comment]
Unfortunately this has not been addressed in PT 2.1.

It is not good to see, that you push back on dealing with security concerns. Especially as you are part of the official PT brand.

I would kindly ask to find a different solution for PTT to access PT's URL.
PTMagic is also capable of doing this.

Thank you.

**Comment by LiamAird** [comment]
Next version will use the apiToken instead of the password.

**Comment by smoochy** [comment]
Thank you.
