### ISSUE TITLE
DCA Entries do not match PT - coin listed twice

### ISSUE THREAD

**Issue by GHuser032018** [bTayFla/PtTracker#62]
i downloaded and setup V2.0 and the DCA screen shows a duplicate coin, making the QTY in DCA higher than the actual DCA log in PT. And the values for the coin are not matching.

![dca](https://user-images.githubusercontent.com/37358200/37383427-bad1f876-2716-11e8-9a30-6fcf94246e4e.JPG)

**Comment by LiamAird** [comment]
Confirmed issue. 
We are looking into it.

**Comment by smoochy** [comment]
Has been resolved for me by updating to 2.0.1, as also stated in the changelog.

And welcome to the MCOETH Bag Club, @GHuser032018 ;)
