### ISSUE TITLE
[Feature Request] Show BNB left

### ISSUE THREAD

**Issue by smoochy** [bTayFla/PtTracker#63]
Hi,

I am sure the overwhelming majority of users on the Binance exchance hodl BNB coin to pay their fees with.
It would be nice, if PTT would display somewhere, what the BNB balance is.
And maybe show an exclamation mark or sth different to catch attention, if the balance drops below 0.5 or a user definable threshold.

Cheers.

**Comment by clownfish44** [comment]
It will show it if its in your pairs...

**Comment by smoochy** [comment]
Well, there is reasons why to disable trading BNB and also hide it from pairs. 
But maybe I do have a wrong idea why I should have a currency, I do only use for paying fees and nothing else, enabled and visible.

**Comment by LiamAird** [comment]
If you are not using it to buy/sell, it will not be shown in Profit Trailer, and if it has no records of buy and sell, it will not show up in PtTracker either. 

We cannot track, what is not traded with. 
Showing disabled pairs would require an API call to your exchange, which is not possible in PtTracker.
