### ISSUE TITLE
Pull Trade API from the Exchanges

### ISSUE THREAD

**Issue by CryptoThriver** [bTayFla/PtTracker#64]
Pull Trade API from Binance -Every time we update PTTracker- the logs get messed up- 

Now that PTTracker is connected to Profit Trailer (congrats on that!)  Can it use the API pull- or have the user open a new API to pull the trades from the exchange- that would give current and accurate numbers no matter what update is done.

**Comment by d4260** [comment]
Best of luck mate but don't think this will ever happen.
We will have to either stop using PT Tracker all together or keep fixing the corruption in the log file that PT Tracker is causing.
Not to shift the blame but maybe the Profit Trailer team can come up with a solution for this one.

**Comment by d4260** [comment]
#6 
#16
#21 
#55

**Comment by clownfish44** [comment]
https://github.com/bTayFla/PtTracker/issues/47

**Comment by CryptoThriver** [comment]
Ok, even if there was an excel spreadsheet that we could import and upload that would build the transaction history and reconcile transactions.  I am sure it is not easy- but it would be very valuable.
