### ISSUE TITLE
[Feature Request] Just a couple of Ideas

### ISSUE THREAD

**Issue by SpinFX007** [bTayFla/PtTracker#65]
Just a couple of Ideas:
1.  First, run setup like and application - Would save your support some work if when you first run the program a GUI prompt for the settings required pops up.  With explanations, would help newbies and the people that are not the best with computers.

2.  Just a little display up the top right to say what Fiat you are viewing tracker in.

3.  On the Daily / Cumulative Profit graph, maybe just a little Key for the lines.

4.  A page to should your current settings of PT.

5.  A status to tell you what market you are in based on your indicators.  Up the top on the Dashboard page.

Ok that enough from me, loving V2.  Keep up the good work.

**Comment by clownfish44** [comment]
https://github.com/bTayFla/PtTracker/blob/master/CONTRIBUTING.md I posted this yesterday and it is on the side when you post an issue.
