### ISSUE TITLE
[Feature Request] Show generated pair config info in each log record

### ISSUE THREAD

**Issue by NigglesSquiggles** [bTayFla/PtTracker#66]
Instead of hunting through the pairs config in PT, I'd love to be able to click some arrow icon in each coin's record in any log page. For example, if I'm looking at my Possible Buy Log and see different strategies, I'd like a quick way to see what each coins config stats are (Price Trend, volatility, volume etc...)
Then I can go to my charts and plot out the strategy and see what I can tweak.

**Comment by clownfish44** [comment]
https://github.com/bTayFla/PtTracker/issues/53
