### ISSUE TITLE
[Feature Request] Change Color of "Daily / Cumulative Profit" to match graph lines

### ISSUE THREAD

**Issue by bks-540** [bTayFla/PtTracker#67]
Change Color of "Daily / Cumulative Profit" on main dashboard to match graph lines, so that "Daily" and "Cumulative Profit" are the same color of their respective lines on the graph.

This will help with quick referencing and will help new users understand which is which.

Thanks,
Bryan

**Comment by clownfish44** [comment]
https://cdn.discordapp.com/attachments/418180220672147457/424218371001810954/debcb26e5b231df0b905bb3af4a0dd01.png

**Comment by bks-540** [comment]
Something like that would work. Definitely would help with quick references instead of having to remember which is which. I'm sure over time you'd remember, but for casual users and/or new users it would really help. 
Thanks!

**Comment by LiamAird** [comment]
planned for 2.1.0
