### ISSUE TITLE
[BUG] (V 2.0.1) Pie chart showing 3% pairs when there are no pairs (should be dust?)

### ISSUE THREAD

**Issue by razorseal** [bTayFla/PtTracker#68]
I don't currently have any pairs, and pairs is showing 3% on the pie chart. I think this is dust, but I'm not sure. Please see my screenshot which should explain it. V2 had this too, but still existing on 2.0.1

![image](https://user-images.githubusercontent.com/34427378/37492562-30d5cf0e-2878-11e8-8752-8644a03ea7fe.png)

**Comment by clownfish44** [comment]
Accepted to be fixed in to 2.0.2
