### ISSUE TITLE
[BUG] Sales Data Empty after specific date

### ISSUE THREAD

**Issue by ssbn** [bTayFla/PtTracker#70]
Just upgraded to PTTracker 2.01, and my sales data stops showing entries in PT Tracker after Feb 25th at 17:02 PM. ProfitTrailer is set to hold 9999 days of data. PT shows entries in the web interface and is otherwise working fine.

**Comment by ssbn** [comment]
![image](https://user-images.githubusercontent.com/29164232/37504872-fc7c0316-28a6-11e8-85f9-870ae2783ad2.png)

There are indeed sales on every day shown here, despite PTTracker showing 0's.

**Comment by ssbn** [comment]
After clearing out the db and journal and reloading, now the data only goes to Feb 19th and stops.

**Comment by clownfish44** [comment]
Anything over 365 days of data will produce this by corrupting new log
