### ISSUE TITLE
[Bug] Negative value shown in Current Holdings -> Profits, though positive

### ISSUE THREAD

**Issue by smoochy** [bTayFla/PtTracker#71]
Heya,

I noticed a little glitch, when looking at the Current holdings table. Although the profit of my two pairs was positive (and had the green color), it showed a minus amount of Euro:

![holdings](https://user-images.githubusercontent.com/34371932/37507875-eb1d0562-28f0-11e8-8a7a-39a345d95cc9.jpg)

V2.0.1, running on Ubuntu 16.04.

Let me know if you need more information.

**Comment by clownfish44** [comment]
Accepted to be fixed in to 2.0.2
