### ISSUE TITLE
[Bug] Time of Sales in PTT incorrect

### ISSUE THREAD

**Issue by smoochy** [bTayFla/PtTracker#73]
I do have a time related bug.

I am living in Germany and have set `server.timeZoneOffset = +01:00` in PT application.properties.
In my PT sales log the time is correct and I do get the Telegram push notifications at the correct time.

Last night short before 1am local time, I was lying in bed, getting notifications about sales. But they did not show up on PTT.

I am talking about the SUBETH sale here, which happened at 0:55am local time (which relates to 12.55am):

![img_0206](https://user-images.githubusercontent.com/34371932/37507186-932706d0-28ed-11e8-8b44-01e1656bc9b4.jpg)

As you can see from the next screenshot, it is not being seen at all by PTT, even 4 minutes later. And it was not counted towards the 15th of March. Looking right now at the amount of sales on 15th of March, it is still 11:

![img_0205](https://user-images.githubusercontent.com/34371932/37507286-063ff6d6-28ee-11e8-9dc8-6911f40ff049.PNG)

After 1am local time, the sale showed up in PTT, but the time was off. Not by 1 hour, but other amounts of minutes:

![img_0207](https://user-images.githubusercontent.com/34371932/37507610-b27571dc-28ef-11e8-936f-760394bbcedf.jpg)

I never really paid attention to the time before, I can not say, if this issue was already present in V2.0 or even in V1.13.

Running Ubuntu 16.04. Fiat is set to EUR. I have enabled SSL. The Botname has no special chars. I have one positive deposit on 03/12/2018. But times are off in PTT as far as my sales history goes, so even before the deposit.
Updated to 2.0.1 last night around 10pm. I already stopped PTT, deleted the pttracker.db and let it recreate. It now has a different size (160KB compared to the original file of 172KB), but all times are still off.

Let me know if you need more information from me to narrow down the cause.

**Comment by alexjbyron** [comment]
I have the same issue! The sale time of a pair is always 3 minutes past the hour it was sold in no matter what time of the hour it sold!

**Comment by clownfish44** [comment]
Both of these issues can not be replicated. Please make sure your offset is in the right format for PT. Also ensure that your pc time is correct. If these do not fix your issue we will assist you  in the discord. 

Windows:
Open a new command prompt as administrator and enter the following commands:
     net start w32time
     w32tm /resync

Mac OS: 
Go to System Preferences, click Date & Time, and ensure the check box is checked for “Set Date and Time Automatically”. Select your time zone and a server that is close to your location if possible.

**Comment by smoochy** [comment]
I can confirm that the V2.0.2 Update fixed the issue.
