### ISSUE TITLE
[Bug] editing TradingView charts is glitchy and crashes safari browser on iPhone. 

### ISSUE THREAD

**Issue by NigglesSquiggles** [bTayFla/PtTracker#75]
I was viewing a chart from within the possible buy log. Tried to alter the volume indicator. 
Changed period ok, and changed moving average from line to area was ok, but trying to edit moving average colour zoomed in way to far then crashed the page, then Safari itself.

**Comment by NigglesSquiggles** [comment]
Also would be nice to view the charts from other time frames. Like 5 minutes or 30 minutes. Could this be set in some kind of settings or preferences menu?

**Comment by clownfish44** [comment]
This is a trading view widget issue. Try a different browser and join the discord and talk with us.
