### ISSUE TITLE
[Feature request] Buy log on Dashboard

### ISSUE THREAD

**Issue by BroTastix** [bTayFla/PtTracker#77]
Under the daily profit table on the dashboard page you guys have a perfect spot for a buy log.
I allways have to go to the exchange site to see what i just recently bought, it would be a big help if we could see this in a glance like all the rest.

This is the only time i need to change screen to get the information. If you guys put in this buy log then everything can be seen on the PtTracker.

Greetz
BroTastix

**Comment by LiamAird** [comment]
May come in 2.1 or in a later version when exchange support is added in.

**Comment by LiamAird** [comment]
Will most likely not be added. Archived.
