### ISSUE TITLE
Export to Excel sheet!

### ISSUE THREAD

**Issue by CryptoSpidey** [bTayFla/PtTracker#8]
It would be wonderful if we can export in Excel sheet format

**Comment by tooraj-enayati** [comment]
Yes, I expected to see this and was disappointed when I couldn't find it.

**Comment by CryptoSpidey** [comment]
Hum, it would be nice, we can run formulas for which coin is good for be which given me shit, Even I can check my profit in INR. I can do lot of things with that raw data.

**Comment by clownfish44** [comment]
It's in next update!
