### ISSUE TITLE
[HOUSE-KEEPING] resource management: RAM

### ISSUE THREAD

**Issue by woodyalien** [bTayFla/PtTracker#81]
Yeah, this is not really a bug nor feature related, but resource management.

Hello PTT team!
I am facing a 'peculiar' situation:

First of all, the SCENARIO: I am currently using PTT 2.0.1, PT 1.2.6.24, on a Windows Server 2016. I run 2 instances: a Bittrex BTC and a Binance ETH. Everything works... up to a certain point.

PROBLEM: I have been noticing extremely high memory usage since v2, but not just high because of the new design and improvements, it is like a sick snow ball that never stops to grow. It happens to the ETH instance ONLY. While the BTC instance stays stable between 60 and 100MB of RAM, the ETH instance allocates increasing amount until it crashes - and it works up to that moment, I access the browser and see that PTT works, but something happens in background that crazily allocates RAM and eventually crashes itself.

And this is recurring situation: it happens no matter having the service restarted or the server rebooted, it always go the same path.

To illustrate RAM allocation and few other factors, below is a perfmon chart with some marks:
The chart shows the last 24 hours; nothing else was changed during this whole period, but only stopping/crashing PTT ETH and restarting it, nothing else; PTT BTC is running without issues for 3 days while PTT ETH goes like described.

- 1st ellipse: I manually stopped PTT ETH when allocating near 1GB of RAM;
- 1st arrow: restarted PTT ETH (notice the increasing RAM allocation)
- 2nd ellipse: PTT ETH crashed/aborted when reached near 1.5GB of RAM allocated for this particular process;
- 2nd arrow: restarted PTT ETH
- 3rd ellipse: PTT ETH crashed again
- after 3rd ellipse: decided to leave it off to monitor the system behavior - flat.

Please guide me thru the data you need to further understand what happens.

![perfmon](https://user-images.githubusercontent.com/35428835/37571718-f2078af4-2b08-11e8-996b-b02a266238f4.jpg)

**Comment by clownfish44** [comment]
@woodyalien please join our discord and tag @support
