### ISSUE TITLE
[Bug] SSL Not Working

### ISSUE THREAD

**Issue by hackley2** [bTayFla/PtTracker#82]
I've had my own domain's LetsEncrypt SSL certificates setup and working more-or-less with ptTracker since v1.13. I was quite thrilled with v2.0.0 came out because it supported full SSL connection (in addition to its other fantastic updates!). To set up ptTracker with my own certs, instead of using the SSL keys provided by default, I symlinked the LetsEncrypt SSL keys like so:

`PtTracker.crt -> /etc/letsencrypt/live/<my-ptt-domain.com>/cert.pem`
`PtTracker.key -> /etc/letsencrypt/live/<my-ptt-domain.com>/privkey.pem`

This worked great until v2.0.2 of ptTracker, when (after restarting the `pm2` service) my PTT installation would only cause the browser (chrome and firefox) to show me a `SSL_ERROR_RX_RECORD_TOO_LONG` error. I tried restarting pm2 several times in different ways, and even restarting the entire VPS. However, out of other things to try I reverted back to v2.0.1 and my PTT installation popped right up no problem!

Of note, just before I updated both Profit Trailer and Profit Trailer Tracker to v1.2.6.25 and v2.0.2 respectively, I did correct the timezone on my VPS using the `timedatectl set-timezone` command. I wouldn't think this could affect SSL certs though.

**Comment by smoochy** [comment]
I faced the same issue after updating to 2.0.2. I also use Lets Encrypt, but without using the PTT certificate at all.
I am running PTT on an Ubuntu 16.04. Nginx is doing my http(s) server stuff.

Starting PTT worked flawlessly, no errors reported in the log file.

In the past I needed to use an entry like this in the `/etc/ngingx/sites-available` to get PTT to run:

```
server {

	listen 443;
	server_name private.domain.tld;

	ssl_certificate		/etc/letsencrypt/live/domainname/cert.pem;
	ssl_certificate_key	/etc/letsencrypt/live/domainname/privkey.pem;

	ssl on;
	ssl_session_cache builtin:1000  shared:SSL:10m;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
	ssl_prefer_server_ciphers on;

	access_log	/var/log/nginx/nginx.log;

	location / {

	proxy_set_header	Host $host;
	proxy_set_header	X-Real-IP $remote_addr;
	proxy_set_header	X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header	X-Forwarded-Proto $scheme;

# Fixes the “It appears that your reverse proxy set up is broken" error.
	proxy_pass	https://localhost:port;
	proxy_read_timeout	90;

	proxy_redirect	https://localhost:port https://private.domain.tld;
	}
}
```

Just out of curioisity, I changed the `proxy_pass	https://localhost:port`; and `proxy_redirect	https://localhost:port` from `https `to `http`, used `service nginx restart` and bam, it worked again.

**Comment by smoochy** [comment]
@bruce133 Not exactly.

With

```
server {
	listen 80;
	return 301 https://$host$request_uri;
}
```
I redirect everything from http://private.domain.tld to https://private.domain.tld and then tell the nginx server which internal port it should forward the request of https://private.domain.tld to.

**Comment by bruce133** [comment]
@smoochy So when connecting to PT, your PTT goes through the following steps, right?

1. Connects to http://_private.domain.tld_
2. Gets redirected to https://_private.domain.tld_
3. Request gets relayed to http://localhost:_port_ (localhost in the server's perspective, with PT's port number)
4. Response from PT gets relayed back, seemingly coming from https://_private.domain.tld_

**Comment by smoochy** [comment]
As I am not an everyday unix user, what you described  is what I think is happening. 

But I do have an own entry for each application. So one for PT, one for PTT, one for Profit Trailer Magic, and one for another instance of PT. 
And each entry has an own private.domain.tld and localhost: port entry.

**Comment by bruce133** [comment]
@smoochy Interesting setup. If I understand correctly, both your PT and your PTT are configured to _not_ use SSL and so communicate freely between each other on the server's localhost, but all external communication passes through Nginx's SSL.

**Comment by smoochy** [comment]
As I do not have a GUI installed on the Ubuntu VPS I do not know exactly if PT could be reached via http://localhost:port or https://localhost:port. But I assume it is via http. In the application.properties file there is nothing to enable SSL.

PT 1.13 did not have SSL support at all. So I could not use it after switching from Windows VPS to Linux VPS.
For PTT 2.0 and 2.0.1 I needed to have the `proxy_pass https://localhost:port`; and `proxy_redirect https://localhost:port` settings active. Now with 2.0.2 it is `http`. Hope it won't switch again with next version :)

**Comment by zapedge** [comment]
so with 2.0.3 ssl is active again, but now it states it is not secure due to an old cypher suite or ssl version
![image](https://user-images.githubusercontent.com/12784954/37723887-cf760fc8-2d2f-11e8-8744-841088563efa.png)

**Comment by smoochy** [comment]
With 2.0.3 I needed to switch back to `proxy_pass https://localhost:port;` and `proxy_redirect https://localhost:port` in my nginx settings.

No issues with unsecure connection using Let's Encrypt certificate.

**Comment by zapedge** [comment]
if you use a reverse proxy the browser connects to the reverse proxy and checks the reverse proxies' cypher suite. therefore @smoochy has no error. But if you have a direct IP connection or NAT/Portforwarding like me, you now get the error. I just bought PTT so i have no access to 2.0.1 to test if it worked back then.

**Comment by zapedge** [comment]
so now i copied the cert and key directly besides the PtTracker binary and it works. 
it did not work with symlinks wich is odd because i have given read rights to others on the specific files in
 
PtTracker.crt -> /etc/letsencrypt/live/<my-ptt-domain.com>/cert.pem
PtTracker.key -> /etc/letsencrypt/live/<my-ptt-domain.com>/privkey.pem

**Comment by hackley2** [comment]
Thanks @smoochy, I too can confirm that v2.0.3 is compatible with symlink'd Let's Encrypt SSL certs. Don't know why the symlinks didn't work for @zapedge but glad copying them in-place worked in that case! Thanks for fixing this. Close this issue out.
