### ISSUE TITLE
[BUG] 2.0.2 Still freezing Multiple Bots

### ISSUE THREAD

**Issue by Binildos** [bTayFla/PtTracker#83]
Hi guys, still got the freezing when changing from dashboard to other screens (PAIRS, POSSIBLE BUYS, etc) when using multiple bot instances.

**Comment by clownfish44** [comment]
Please post this in the discord and talk to @rireal#2742

**Comment by Binildos** [comment]
I already did, and @Rireal#2742 told me to open an issue here... you guys have to improve your communication.

**Comment by clownfish44** [comment]
Use 2.0.3 we fixed it
