### ISSUE TITLE
[Feature Request] Downloading files from PTT

### ISSUE THREAD

**Issue by Binildos** [bTayFla/PtTracker#84]
Talking about the CSV file, it would be awesome if I could save the screen as a report (with all the colorful parts we see in PTT), so I could print it later to study or send by e-mail. This Shoul be available for all PTT screens.

**Comment by clownfish44** [comment]
Not going to happen as sending this by email would entail commercial use...

**Comment by Binildos** [comment]
Well, I told that to @Rireal#2742 and he said it was a great idea... I'll have to talk to him again

**Comment by aludden** [comment]
The JSON file seems to have a lot more detail than the screens and/or PT exports. It would be really useful to export the full data to csv/excel so it can be further analyzed. You wouldn't have to do any custom reports, just a full dump. Thanks!

**Comment by LiamAird** [comment]
Excel and CSV were added in the previous releases. 
Nothing more is planned at this stage.
