### ISSUE TITLE
[Feature Request] Top right of PtTracker 

### ISSUE THREAD

**Issue by BroTastix** [bTayFla/PtTracker#87]
Hi,

In the top right corner of PtTracker you'll see : 
- Balance
- TCV
- TPV
- AVG Daily Profit

Can you make it sow, when you hover with your mouse over the amount that it shows the entire amount? We trade in crypto not in "$", 0.001 in balance can mean 0.0009 or for example 0.0025BTC min buy cost, balance shows 0.002BTC -> I have to go look on the exchange to see how much balance i really got, to manualy DCA/buy new pair. Hovering over it and showing the correct and full balance will make things a bit faster. Great to have all this information in one place! Great work! V2.0 is gorgeous!
Also maybe add the following:
- Top 50 Coin trend Short term %
- Top 50 Coin trend Long term %

DCA values are choosen buy the trend that is present at the time, showing the Top 50 Coin trend % will give users the needed information to know in what kind of trend we are working in. We must not forget that Profit trailer needs some tweaking, this means that if we want to use PtTracker as a standard, it should show us as mutch information as possible, sow we can see the progress made by the changes.
Incredible add-on!

Greetz

**Comment by LiamAird** [comment]
Please keep one bug/feature request per github issue.
Top trends are coming in one form or another in 2.1. 

We will look into the hoverable values.

**Comment by LiamAird** [comment]
Implemented for 2.1
