### ISSUE TITLE
Daily profit on dashboard dosn't match sales log

### ISSUE THREAD

**Issue by woody43567** [bTayFla/PtTracker#88]
In my dashboard it doesn't show the sales information for the current day until mid afternoon.
However, in the sales log I can see multiple sales. My profit trailer is using +10 time zone . I have a feeling that the daily profit section of the dashboard is using a different time zone to the sales log.

![image](https://user-images.githubusercontent.com/36909568/37743267-63a9c670-2dbd-11e8-8f23-a74670e3c6c2.png)

![image](https://user-images.githubusercontent.com/36909568/37743274-6bf4e382-2dbd-11e8-84f7-c26dd75670c5.png)

**Comment by clownfish44** [comment]
Join the discord and tag @support

**Comment by woody43567** [comment]
This is with the current version of tracker (v2.0.3). Still happening again today.
![image](https://user-images.githubusercontent.com/36909568/37802315-163c5f58-2e7e-11e8-9b9a-afb7634a4d3e.png)
![image](https://user-images.githubusercontent.com/36909568/37802319-1b5026f0-2e7e-11e8-9671-aa9d000cbc15.png)

**Comment by woody43567** [comment]
Hi,
This is happening with the latest version (v2.0.3).
I have updated with some new screenshots today as it is still happening.

Regards,

Josh Wood


E-Mail Disclaimer:
The Information in this e-mail is confidential and may be legally privileged. It is intended solely for the addressee. Access to this e-mail by anyone else is unauthorised. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful. Any opinions or advice contained in this e-mail are confidential and not for public display.
