### ISSUE TITLE
[Feature Request] "Sales" log page displays total (USD) sales to date in the header area.

### ISSUE THREAD

**Issue by TeleTubby9** [bTayFla/PtTracker#90]
Please include in the "Sales" log  a total sales to date amount in (USD) or whatever the users country base currency they would like displayed. 

The data could be posted in the header as "Total Sales To Date - $XX.xx"

**Comment by LiamAird** [comment]
Planne for 2.1

**Comment by LiamAird** [comment]
Implemented in 2.1
