### ISSUE TITLE
Issues with Bittrex TradingView

### ISSUE THREAD

**Issue by Tryptaphonics** [bTayFla/PtTracker#91]
Still getting invalid symbol error.

![screenshot 1](https://user-images.githubusercontent.com/37426660/37864629-fc702986-2f47-11e8-8e36-ffe86328616d.png)

**Comment by Tryptaphonics** [comment]
![screenshot 2](https://user-images.githubusercontent.com/37426660/37864650-51c7f904-2f48-11e8-9e1d-3c2aa45f0752.png)

**Comment by abdellahnaim** [comment]
Same thing for Poloniex.

<img width="1380" alt="screen shot 2018-04-21 at 9 46 09 pm" src="https://user-images.githubusercontent.com/3009038/39088626-72784e44-45ad-11e8-9a6a-3af60c12ab75.png">

**Comment by LiamAird** [comment]
Fixed in version 2.1.1
