### ISSUE TITLE
profits displaying incorrectly

### ISSUE THREAD

**Issue by bowechaim** [bTayFla/PtTracker#92]
the profits display within the gui are inconsistent with profit trailer.

the profit %'s line up and are the same as pt.

please see uploaded screen captures.

![profit-trailer-profits](https://user-images.githubusercontent.com/36929439/37865884-f49a24ee-2f3f-11e8-8b0d-0a476e1a3012.png)
![pttracker-profits](https://user-images.githubusercontent.com/36929439/37865885-f4c90840-2f3f-11e8-819d-e8738f32a906.png)

**Comment by LiamAird** [comment]
Profit Trailer is always showing the current price value for your profits. 
Tracker is showing the value of the closing price of the base pair, giving you a better indication of what you earned that day.

**Comment by bowechaim** [comment]
thanks for the update. 

I hear what you are saying, however, that does not make sense.
1) profits are a closed transaction in time. why would you have pt tracker display the current value??
2) can you clarify what you mean by the "value of the closing price of the base pair"?

**Comment by LiamAird** [comment]
When you sell off a pair you make x crypto (y $). 
We monitor what the dollar value was at the time of the sell, instead of always making it fluctuate with the current standard. 
So if you sold off a pair, when BTC was at 7.000$ it would record that, if you sold another at 8.500$ it would show that value. Both of these will not go up and down because, at the time of the sell, the price was at certain state. 

The way PT is showing it is to always show the sales at the current value - which makes very little sense tbh.

**Comment by bowechaim** [comment]
again, understood.
thanks for the clarification.
Profit trailer works the same.
once the transaction is closed, profit trailer reports the profits. when i look in my sales log within profit trailer, those profits are hard recorded, they do not change with the market price changes.

**Comment by bowechaim** [comment]
so i still do not see the difference with profit trailer and pt tracker.

**Comment by LiamAird** [comment]
They are not in PT. 
If you keep an eye on the sales log (or any log for that matter) the USD profit will change, once the prices changes. 
I just double checked, and it does change.

**Comment by bowechaim** [comment]
the price fluctuates, however, the profits do not.
please review again.
i have been staring at my sales log now for 5 minutes and there is no change, it is static.
all other queues - like pairs log, dca log are dynamic and numbers are changing there.

**Comment by LiamAird** [comment]
Profits do not, no. 
However the USD price in PT fluctuates (sales log: https://www.screencast.com/t/jYN2dmA4G), whenever the base currency changes price. 

We track what you earned in the moment of the sale.

**Comment by bowechaim** [comment]
k, i now have seen my profits change.
that is ridiculous that profit trailer does that, however, i understand why they would choose to do it like that.
thanks for your time and patience.
