### ISSUE TITLE
Not using relative paths

### ISSUE THREAD

**Issue by BitRacer** [bTayFla/PtTracker#94]
I have pttracker running behind a proxy, but because of the absolute paths, I'm unable to view pttracker.  Please use relative paths.

example:
I proxy / to profittrailer
https://my.public.hostname/ -> localhost:8081
I proxy /tracker to pttracker
https://my.public.hostname/tracker/ -> localhost:3000

I get back a page with the following
<script type="text/javascript" src="/manifest.js"></script><script type="text/javascript" src="/vendor.js"></script><script type="text/javascript" src="/client.js"></script></body>

since /manifest.js /vendor.js and /client.js are absolute paths, they just fail

relative paths would create requests for /tracker/manifest.js, /tracker/vendor.js, etc which would be proxied just fine.

**Comment by BitRacer** [comment]
FWIW, I was finally able to woraroudn this with a few filters in nginx

  location /tracker/ {
    #with filters
    subs_filter_types application/javascript;
    subs_filter href="/ href=" g;
    subs_filter src="/ src=" g;
    subs_filter /api api g;
    proxy_pass http://127.0.0.1:3000/;
  }

so these are the three things you need to fix

**Comment by clownfish44** [comment]
Use workaround posted above!
