### ISSUE TITLE
Fix Pairs Bought date

### ISSUE THREAD

**Issue by zapedge** [bTayFla/PtTracker#97]
![image](https://user-images.githubusercontent.com/12784954/38056284-612ab142-32dc-11e8-9a6c-da7363314225.png)

In Pairs view  Bought Date no Timestamp is shown, just the date. DCA and sales showing it.

![image](https://user-images.githubusercontent.com/12784954/38056526-eb3806f0-32dc-11e8-8316-51de5b8cdb53.png)

In PT it is shown. could you please fix this.

It would also be nice if the date/time format could be altered, hence Europe and uses 24h clock not 12am/pm

**Comment by LiamAird** [comment]
Date time is coming in 2.1
24 hour clock format has not yet been planned. Please keep one feature request per ticket.
